### ISSUE TITLE
[vite]: Rollup failed to resolve import "assets/cumulative_budgets.png" from "/home/runner/work/PACKAGE_NAME.jl/PACKAGE_NAME.jl/docs/build/.documenter/index.md"

### ISSUE THREAD

**Issue by shayandavoodii** [LuxDL/DocumenterVitepress.jl#120]
Could you please help me with this error: https://github.com/shayandavoodii/OnlinePortfolioSelection.jl/actions/runs/8895424510/job/24425728076#step:6:54
Here is the link to the related branch: https://github.com/shayandavoodii/OnlinePortfolioSelection.jl/tree/Vitepress

This is the error I got when I tried to build the docs locally:
```
E:\Julia Forks\OPS.jl\docs>npm run docs:dev

> docs:dev
> vitepress dev build/.documenter

failed to start server. error:
Error: ENOENT: no such file or directory, lstat 'E:\Julia Forks\OPS.jl\docs\build\.documenter'
    at Object.realpathSync (node:fs:2702:29)
    at windowsSafeRealPathSync (file:///E:/Julia%20Forks/OPS.jl/docs/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:12590:17)
    at getRealPath (file:///E:/Julia%20Forks/OPS.jl/docs/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:47444:20)
    at getFsUtils (file:///E:/Julia%20Forks/OPS.jl/docs/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:47160:29)
    at preAliasPlugin (file:///E:/Julia%20Forks/OPS.jl/docs/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:49643:21)
    at resolvePlugins (file:///E:/Julia%20Forks/OPS.jl/docs/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:50359:9)
    at resolveConfig (file:///E:/Julia%20Forks/OPS.jl/docs/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:68250:30)
    at async _createServer (file:///E:/Julia%20Forks/OPS.jl/docs/node_modules/vite/dist/node/chunks/dep-C-KAszbv.js:64503:20)
    at async createDevServer (file:///E:/Julia%20Forks/OPS.jl/docs/node_modules/vitepress/dist/node/cli.js:403:20)
```

**Comment by avik-pal** [comment]
You are probably trying to display an image in the markdown https://github.com/shayandavoodii/OnlinePortfolioSelection.jl/actions/runs/8895424510/job/24425728076#step:6:47 which doesn't exist in that path

**Comment by shayandavoodii** [comment]
>  which doesn't exist in that path

Which path?

**Comment by shayandavoodii** [comment]
> You are probably trying to display an image in the markdown https://github.com/shayandavoodii/OnlinePortfolioSelection.jl/actions/runs/8895424510/job/24425728076#step:6:47 which doesn't exist in that path

I changed the path from `assets/cumulative_budgets.png` to:
```@raw html
<img src="src/assets/cumulative_budgets.png" width="100%">
```
For GitHub actions, the former error exists as before.
Locally, when I want to build the documentation, I get the following 403 Error:
![image](https://github.com/LuxDL/DocumenterVitepress.jl/assets/52105833/aab6df8f-ef67-4af9-bf71-e0946f56fe13)

**Comment by asinghvi17** [comment]
@shayandavoodii it looks like you're using a pretty strange way of including images.  That's why the loading doesn't work (that plus your HTML tags weren't closed).  

In this case, you should include your images in the standard Markdown format:
```md
![alt-text](path/to/image)
```
and it will work automatically.

I've tested that on my machine and the docs seem to build fine.

**Comment by shayandavoodii** [comment]
Thank you so much. I used `![alt-text](assets/performance_eval.png)` in the `docs\src\performance_eval.md` and `![alt-text](assets/cumulative_budgets.png)` in `docs\src\index.md`. Yet, the 404 error is there when I try to test it locally. What's the problem?. However, it seems that the problem is solved on GitHub actions: https://github.com/shayandavoodii/OnlinePortfolioSelection.jl/actions/runs/8900200497/job/24441242896#step:6:56

**Comment by asinghvi17** [comment]
Might be because of the `base` URL that's set when dev'ing locally.
